name: Test deploy

on:
  push:
    branches:
      - zhiger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Prepare .env for production
        run: cp .env.production .env

      - name: Deploy using rsync over SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          rsync -avz --delete \
            --exclude=writable \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./ ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }}:/var/www/technology
